app/models.py
from flask_login import UserMixin

from . import db, login_manager


@login_manager.user_loader
def current_user(user_id):
    return User.query.get(user_id)


books_in_users = db.Table(
    "books_users",
    db.Column("user_id", db.Integer, db.ForeignKey("users.id"), nullable=False),
    db.Column("book_id", db.Integer, db.ForeignKey("books.id"), nullable=False),
)


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(84), nullable=False)
    email = db.Column(db.String(84), nullable=False, unique=True, index=True)
    password = db.Column(db.String(255), nullable=False)
    profile = db.relationship("Profile", backref="user", uselist=False)
    books = db.relationship(
        "Book",
        secondary=books_in_users,
        lazy=True,
        backref=db.backref("users"),
    )

    def __str__(self):
        return self.name


class Profile(db.Model):
    __tablename__ = "profiles"
    id = db.Column(db.Integer, primary_key=True)
    photo = db.Column(db.Unicode(124), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def __str__(self):
        return str(self.user_id)


class Book(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(125), nullable=False)

    def __repr__(self):
        return self.name

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    BooleanField,
    PasswordField,
    SelectField,
    StringField,
    SubmitField,
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length

from app.models import Book


class LoginForm(FlaskForm):
    email = EmailField("Email")
    password = PasswordField(
        "Senha",
        validators=[Length(3, 6, "O campo deve conter entre 3 à 6 caracters.")],
    )
    remember = BooleanField("Permanecer Conectado")
    submit = SubmitField("Logar")


class RegisterForm(FlaskForm):
    name = StringField(
        "Nome Completo",
        validators=[DataRequired("O campo é obrigatório")],
    )
    email = EmailField("Email")
    password = PasswordField(
        "Senha",
        validators=[Length(3, 6, "O campo deve conter entre 3 à 6 caracters.")],
    )
    submit = SubmitField("Cadastrar")


class BookForm(FlaskForm):
    name = StringField(
        "Titulo do Livro",
        validators=[DataRequired("o campo é obrigatório")],
    )
    submit = SubmitField("Salvar")


class UserBookForm(FlaskForm):
    book = SelectField(
        "Livro",
        coerce=int,
    )
    submit = SubmitField("Salvar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.book.choices = [(book.id, book.name) for book in Book.query.all()]

app/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from .config import Config

db = SQLAlchemy()
login_manager = LoginManager()
bootstrap = Bootstrap()
login_manager.login_view = "login.html"
login_manager.login_message_category = "danger"


def creat_app():
    app = Flask(__name__, static_folder="public")
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    from . import admin as administrator

    admin = Admin(app, name="OrgContact", template_mode="bootstrap3")
    administrator.init_app(admin)

    from app import routes

    routes.init_app(app)

    return app

app/book/__init__.py
from flask import Blueprint

book = Blueprint("book", __name__)

from . import views

app/book/views.py
from app import db
from app.forms import BookForm, UserBookForm
from app.models import Book
from flask import flash, redirect, render_template, url_for
from flask_login import current_user

from . import book


@book.route("/book/add", methods=["GET", "POST"])
def book_add():
    form = BookForm()
    if form.validate_on_submit():
        book = Book()
        book.name = form.name.data
        db.session.add(book)
        db.session.commit()

        flash("Livro cadastrado com sucesso", "success")
        return redirect(url_for(".book_add"))

    return render_template("book/add.html", form=form)


@book.route("/user/<int:id>/add-book", methods=["GET", "POST"])
def user_add_book(id):
    form = UserBookForm()
    if form.validate_on_submit():
        book = Book.query.get(form.book.data)
        current_user.books.append(book)

        db.session.add(current_user)
        db.session.commit()

        flash("Livro cadastrado com sucesso", "success")
        return redirect(url_for(".user_add_book", id=current_user.id))

    return render_template("book/user_add_book.html", form=form)

app/routes.py
from app.auth import auth as auth_blueprints
from app.book import book as book_blueprints
from app.users import users as users_blueprints


def init_app(app):
    app.register_blueprint(auth_blueprints)
    app.register_blueprint(book_blueprints)
    app.register_blueprint(users_blueprints)

app/users/__init__.py
from flask import Blueprint

users = Blueprint("users", __name__)

from . import views

app/users/views.py
from app import db
from app.models import User
from flask import redirect, render_template, url_for
from flask_login import login_required

from . import users


@users.route("/")
def index():
    users = User.query.all()  # Select * from users
    return render_template("index.html", users=users)


@users.route("/user/<int:id>")
@login_required
def unique(id):
    user = User.query.get(id)
    return render_template("user.html", user=user)


@users.route("/user/delete/<int:id>")
def delete(id):
    user = User.query.filter_by(id=id).first()
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for(".index"))


@users.route("/redirect")
def redirectt():
    return redirect(url_for(".response"))


@users.route("/response")
def response():
    return render_template("response.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">

    {% block styles %}
        {{ bootstrap.load_css() }}
    {% endblock styles %}

</head>
    <body>
        {% include 'components/navbar.html' %}
        <div class="container">
            
            {% block content %} {% endblock content %}

        </div>

        {% block conteudo %}

        {% endblock %}

        <!-- Separate Popper and Bootstrap JS -->
        {% block scripts %}
            {{ bootstrap.load_js() }}
        {% endblock %}
    </body>
</html>

app/templates/book/add.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    {% include 'components/notification.html'%}
    {{ render_form(form) }}
{% endblock %}

app/templates/book/user_add_book.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
    {% include 'components/notification.html'%}
    {{ render_form(form) }}
{% endblock %}

app/templates/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for ('users.index') }}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        {% if not current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.register') }}">Registrar</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Sair</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('book.book_add') }}">Add Livros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

app/templates/components/notification.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, sms in messages %}
            <div class="alert alert-{{category}} text-center" role="alert">
                {{ sms }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/index.html
{% extends 'base.html' %}


{% block content %}

<div class="alert alert-danger">
    <h1 class="text-center">Página de index</h1>
</div>
{% if current_user.is_authenticated %}
    <div>
        {% for user in users %}
            <ul>
                <li> <a href="{{ url_for ('users.unique', id=user.id) }}">{{user.name}}</a> </li>
            </ul>
        {% endfor %}
    </div>
    <div>
        <h3><a class="text-center" href="{{ url_for ('auth.register') }}">Registrar</a></h3>
    </div>
{% endif %}


{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}

    {{render_form(form)}}
    
    {% include 'components/notification.html' %}

{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}

    {{render_form(form)}}
    {% include 'components/notification.html' %}

{% endblock content %}

app/templates/response.html
{% extends 'bootstrap/base.html' %}

{% block content %}
<div class="alert alert-danger">
    <h1 class="text-center">Página de response</h1>
</div>
{% endblock content %}

app/templates/user.html
{% extends 'base.html' %}

{% block content %}
    <a href="{{ url_for('users.index') }}" class="btn btn-info mt-3">Voltar</a>
    <a href="{{ url_for('book.user_add_book', id=user.id) }}" class="btn btn-success mt-3">Adicionar Livro</a>

    <table class="table table-hover mt-3">
        <tbody>
            <tr>
                <td scope="row">{{ user.id }}</td>
                <td scope="row">{{ user.name }}</td>
                <td scope="row" colspan="2" class="text-center">{{ user.email }}</td>
                <td scope="row">{{ user.profile.photo }}</td>
                <td scope="row">
                    <a class="text-center btn btn-danger btn-sm"
                        href="{{ url_for ('users.delete', id=user.id) }}">
                            <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>

    <h2 class="text-muted">Books:</h2>

    <ul class="list-group list-group-flush">
        {% for book in user.books %}
            <li class="list-group-item">
                {{ book.name }}
            </li>
        {% endfor %}

    </ul>
{% endblock content %}